# Permalinks
permalink:           pretty
#relative_permalinks: true // Commented out due to https://github.com/poole/lanyon/issues/124#issuecomment-155645090
plugins:
  - jekyll-paginate

# Setup
title:               Tamil Meme Guide
tagline:             'A meme course for Tamil Meme nation'
description:         'A no-nonsense meme guide for Tamil Meme'
url:                 https://lanyon.netlify.com
baseurl:             ''
paginate:            5
paginate_path: "page:num"

# About/contact
author:
  name:              Sanjeev NC
  url:               https://keybase.io/oedmarap
  email:             yenceesanjeev@gmail.com

# Custom vars
#version:             1.0.0 // Commented out so user can decide on versioning later. Also not necessary for frontmatter.
