# Permalinks
permalink:           pretty
#relative_permalinks: true // Commented out due to https://github.com/poole/lanyon/issues/124#issuecomment-155645090
plugins:
  - jekyll-paginate

# Setup
title:               Tamil Meme Guide
tagline:             'A comprehensive guide on Tamil Meme Creation with examples'
description:         'A comprehensive guide on Tamil Meme Creation with examples'
url:                 https://lanyon.netlify.com
baseurl:             ''

# About/contact
author:
  name:              Sanjeev NC
  email:             yenceesanjeev@gmail.com

# Custom vars
#version:             1.0.0 // Commented out so user can decide on versioning later. Also not necessary for frontmatter.
